### ISSUE TITLE
Unable to load bundle details into canvas

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#1685]
See https://github.com/CanonicalLtd/jujucharms.com/issues/268

**Comment by frankban** [comment]
Hey Antonio,
I tried following your same steps but I was not able to reproduce the issue.
I am running the GUI in Juju 2.1.2 with Juju 2 compiled from master trunk.
Could you please confirm that this is still an issue for you?

**Comment by arosales** [comment]
Seems Jorge Castro also recently hit this problem.  I will try to recreate with the latest released Juju 2, which as of this writing is Juju 2 beta 8.

**Comment by arosales** [comment]
I was able to easily produce this in the Juju 2, beta8 GUI. I was deploying against aws-east-2 searching for "observable-swarm" and I got the unable to load bundle details as also stated in https://github.com/CanonicalLtd/jujucharms.com/issues/268
```
$ juju version
2.0-beta8-xenial-amd64
```

![screen shot 2016-06-15 at 5 12 38 pm](https://cloud.githubusercontent.com/assets/1707853/16100700/6532905e-331d-11e6-9841-16a7ee16bca1.png)

**Comment by hatched** [comment]
@arosales It looks like you're using a quite old version of the GUI. This has been fixed in the development branch of the GUI and a release will probably be made in another weeks time.

**Comment by arosales** [comment]
@hatched I am using the current released beta8 version of the GUI. From a user perspective there is no more recent version. I would suggest to leave this open until it can be verified in a "released" even if beta version.

**Comment by arosales** [comment]
I am still unable to load bundle details for observable-swarm (as an example) in the latest juju 2.0 beta9 release.

![screen shot 2016-06-17 at 3 21 59 pm](https://cloud.githubusercontent.com/assets/1707853/16165188/bd48a20a-349f-11e6-83d5-96b38454b1b3.png)

**Comment by arosales** [comment]
This looks better in the charm store update using juju2 beta9

![load-k8](https://cloud.githubusercontent.com/assets/1707853/16202618/af05e76c-36d3-11e6-9cd0-8e92b92289c6.png)
![swarm-load](https://cloud.githubusercontent.com/assets/1707853/16202617/af054424-36d3-11e6-883d-d01a6bd0d38c.png)

**Comment by hatched** [comment]
Thanks for reporting back that this is back up and running. Also please see https://github.com/juju/juju-gui/issues/1780#issuecomment-227226545 if you're having issues deploying the bundle.
