### ISSUE TITLE
Bundle search is broken

### ISSUE THREAD

**Issue by arosales** [juju/juju-gui#1765]
When searching for any bundle I am unable to locate it. The GUI returns 0 results when I know there are numerous. Examples are "apache" or "hadoop."  

Some users would like to deploy bundles via the gui and without remembering the URL searching is the next best option, however the GUI is not showing bundle results. I am using the GUI in the latest Juju 2.0 gui (beta 8).

```
~$ juju version
2.0-beta8-xenial-amd64
```

![screen shot 2016-06-15 at 5 13 40 pm](https://cloud.githubusercontent.com/assets/1707853/16100794/1f851102-331e-11e6-8907-3c6ae368ba67.png)
![screen shot 2016-06-15 at 5 14 12 pm](https://cloud.githubusercontent.com/assets/1707853/16100795/1f88b99c-331e-11e6-9d01-985550c3d21e.png)

**Comment by arosales** [comment]
As a side note this is the way a lot of solution architects demonstrate to users as the GUI provides an easy talking point when demonstrating Juju.

**Comment by urosj** [comment]
@arosales we're exploring different search algorithms in order to return more direct results. We're updating this failed one early next week.

**Comment by hatched** [comment]
It appears that you're using an older version of the GUI. These bugs have been resolved in the development branch of the GUI and we're hoping to get a new release out in a weeks time.

**Comment by arosales** [comment]
@urosj thanks for the info.

@hatched I am using the _current_ released beta8 version of the GUI. From a user perspective there is no more recent version. I would suggest to leave this open until it can be verified in a "released" even if beta version.

**Comment by arosales** [comment]
Search is still broken in the latest juju 2.0 beta9 release. Searching for "hadoop" and clicking on bundles only returns 1 result and the one result isn't a recommended charm. There are many bundles with hadoop in the name that should be displayed, namely hadoop-processing.

![screen shot 2016-06-17 at 3 22 34 pm](https://cloud.githubusercontent.com/assets/1707853/16165139/748461e4-349f-11e6-9a52-cea3fe92b692.png)

**Comment by mitechie** [comment]
I am going to guess https://github.com/juju/charmstore/issues/639 is related to this and we should track that deployment and double check the issue exists without a GUI update.

**Comment by mitechie** [comment]
Is this corrected with the latest deploy? https://demo.jujucharms.com/?search=apache%20hadoop

**Comment by arosales** [comment]
This looks a lot better in the recent update

![hadoop-search-working](https://cloud.githubusercontent.com/assets/1707853/16202532/3e9b1682-36d3-11e6-9629-85e1d7b8d028.png)

**Comment by hatched** [comment]
As it appears this bug is resolved and not a GUI issue I'll close this Issue.
