### ISSUE TITLE
GUI ignores config values for bundle

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#2845]
Moved from https://bugs.launchpad.net/juju-gui/+bug/1688159

Juju 2.1.2 / webui 2.5.2

Configuration options for a charm are ignored when deploying a bundle via the Web UI and instead, the charm default value is used

Steps to reproduce:

1) Add cs:bundle/openstack-base-49 to the canvas
2) Modify network-manager in Nova Cloud Controller charm so that it is 'Neutron'
3) Deploy bundle
4) After deployment, network-manager config will revert to default 'FlatDHCPManager'

The same is not reproducible via the CLI: juju deploy cs:bundle/openstack-base-49

**Comment by frankban** [comment]
Ok I deployed `openstack-base/bundle/49` via the GUI, and it seems that "Neutron" is the default value for the `nova-cloud-controller`'s network-manager option (see [1]). Anyway, I changed it to "FlatDHCPManager" to check that it sticks, and after deploying the bundle I've found the new value to be correctly set. Did you click the "Save changes" button at the bottom of the inspector after changing the configuration value? If so, could you provide more info on how to dupe the bug? Thanks!

[1] https://api.jujucharms.com/charmstore/v5/bundle/openstack-base-49/archive/bundle.yaml

**Comment by frankban** [comment]
Feel free to reopen this bug if this is still a problem, thanks!

**Comment by sa-kura** [comment]
This problem have still occured in my environment.
I used Juju 2.2.0 and webui 2.7.3.

I want to set "Neutron" in network-manager with GUI deployment, but it is set "FlatDHCPManager".
"Neutron" in bundle.yaml is ignored , and "FlatDHCPManager" of the default value in "Nova Cloud Controller charm" appears to be applied.

For reproduce, you need to change from "FlatDHCPManager" to "Neutron" with the GUI deployment.

**Comment by frankban** [comment]
Cool, thanks for reporting, we'll investigate this again.

**Comment by frankban** [comment]
Confirmed, I am working on a fix.

**Comment by frankban** [comment]
The fix is landed, it will be available as part of the next release. Thank you!
